### ISSUE TITLE
Would it be possible to run the generator for all classes that are specified in types.properties?

### ISSUE THREAD

**Issue by Dierk** [Frege/frege-native-gen#13]
Giving one class at a time is ok while incrementally building up a suite but for a batch-like processes it is a lot of extra work and we could reuse the declaration that we already did in the types.properties file.

**Comment by mmhelloworld** [comment]
It is now possible to generate for an entire package and all its sub packages. An improvement upon this I have planned is to be able to pass a list of classes.

**Comment by mmhelloworld** [comment]
There is now a `-c <comma-separated list of class names>` option which allows us to be able to generate for a specific set of classes. We can now specify a package name or a set of classes to generate native declarations. More information on this here: https://github.com/Frege/frege-native-gen#how-to-run .
