### ISSUE TITLE
adding location for types.properties

### ISSUE THREAD

**Issue by Dierk** [Frege/frege-native-gen#15]
At the moment, it is quite unclear where that file is expected.
It would also be helpful if one could specify on the command line, where that file is located.

**Comment by mperry** [comment]
I found this location when experimenting with the gradle plugin, so it was unclear to me too.

**Comment by mmhelloworld** [comment]
I have updated the code such that the file is now part of release and is not an input anymore.  When the release archive is extracted into some folder, and the application is invoked from that folder, it is read from that folder automatically. It is basically read from the current folder now and is not an input.
