### ISSUE TITLE
frege-native-gen:1.3 is strong coupled to frege-lang:3.22.367-g2737683

### ISSUE THREAD

**Issue by jwausle** [Frege/frege-native-gen#30]
frege-native-gen:1.3 can only be used in that gradle-configuration 'build.gradle'

```
plugins {
   	id "org.frege-lang" version "0.5"
}

dependencies {
    compile "org.frege-lang:frege:3.22.367-g2737683"
    compile "org.frege-lang:frege-native-gen:1.3"
}

fregeNativeGen {
    className = "java.util.function.Function"
}

```

$ gradle fregeNativeGen # successful generated 'build/generated/frege/NativeGenOutput.fr'

The following 'org.frege-lang:frege:*' are NOT usable
-     wether ClassNotFoundExceptions
-     or NoSuchMethodeError
-     or simular type-exceptions

In compatible versions:
-     org.frege-lang:frege:3.23.422-ga05a487
-     org.frege-lang:frege:3.23.401-g7c45277
-     org.frege-lang:frege:3.23.370-g898bc8c
-     org.frege-lang:frege:3.23.288-gaa3af0c
-     org.frege-lang:frege:3.22.524-gcc99d7e

**Comment by Ingo60** [comment]
Hint: It would probably be better to generally recompile apps.

However, binary compatibility cannot be expected in any case between 3.22 and 3.23.

**Comment by jwausle** [comment]
Maybe... From my point of view frege-native-gen should have the same version than frege self. Because both are strong coupled (on binary level). If I want to use both together in on configuration (like above). I need to know this binary relationship. Thats confusing.

**Comment by mmhelloworld** [comment]
frege-native-gen has been updated to `3.23.450-SNAPSHOT`. This should be compatible with the latest version of Frege. Please try now and if it doesn't work, please reopen the issue.
