### ISSUE TITLE
Publishing on Maven Central

### ISSUE THREAD

**Issue by ftomassetti** [Frege/frege-native-gen#4]
Is there any plan to publish it on Maven Central? Can I help?

**Comment by mmhelloworld** [comment]
Sorry, I couldn't respond to this earlier. Now that we have a group to publish artifacts https://oss.sonatype.org/content/groups/public/org/frege-lang/ , there shouldn't be a problem to get this into maven central. @ftomassetti would you still be able to help on this?

**Comment by ftomassetti** [comment]
No problem, I have been following the discussion in the mailing-list. Let me know if there is something specific I can help with, otherwise I will follow the mailing list and look for occasions to make myself useful

**Comment by talios** [comment]
All being well I'll republish my bundle under the new groupId today.

**Comment by mperry** [comment]
Thanks for the offer to help @ftomassetti.   As you are probably aware, this is now on Maven Central.  I would encourage you to get involved and contribute in any way you can.  We need all the capable people we can get.
